language: java
jdk:
   - openjdk11
script: ant build

addons:
  sonarcloud:
    organization: mihai998
    token: f329172194d5a9ac8d7e60784a7b5fa6d0ae491e
script:
- ant build
- sonar-scanner